#!/usr/bin/env python3
import requests
import json
import os
import sys

CONSUL_HOST = os.getenv('CONSUL_HOST', '192.168.50.100')
CONSUL_PORT = os.getenv('CONSUL_PORT', '8500')
SERVICE_NAME = os.getenv('SERVICE_NAME', 'fengbushi-chat')
NGINX_CONFIG_PATH = os.getenv('NGINX_CONFIG_PATH', '/etc/nginx/conf.d/fengbushi-upstream.conf')

def get_healthy_services():
    url = "http://%s:%s/v1/health/service/%s?passing" % (CONSUL_HOST, CONSUL_PORT, SERVICE_NAME)
    try:
        response = requests.get(url, timeout=5)
        response.raise_for_status()
        services = response.json()
        
        healthy_instances = []
        for service in services:
            node = service['Node']
            svc = service['Service']
            address = svc.get('Address') or node.get('Address')
            port = svc.get('Port')
            if address and port:
                healthy_instances.append({
                    'address': address,
                    'port': port,
                    'instance_id': svc.get('ID', '')
                })
        return healthy_instances
    except Exception as e:
        sys.stderr.write("Error fetching services from Consul: %s\n" % e)
        return []

def generate_nginx_config(instances):
    if not instances:
        return ""
    
    config_lines = [
        "# Auto-generated by consul-template.py",
        "upstream fengbushi_backend {",
        "    least_conn;",
        ""
    ]
    
    for instance in instances:
        config_lines.append(
            "    server %s:%s max_fails=3 fail_timeout=30s;" % (instance['address'], instance['port'])
        )
    
    config_lines.extend(["}", ""])
    return "\n".join(config_lines)

def main():
    instances = get_healthy_services()
    if instances:
        config = generate_nginx_config(instances)
        with open(NGINX_CONFIG_PATH, 'w') as f:
            f.write(config)
        os.system('nginx -t && nginx -s reload')
        print("Updated Nginx config with %d instances" % len(instances))
    else:
        print("No healthy instances found")

if __name__ == '__main__':
    main()
